import { createAction, createAsyncActions } from '../../utils';

const API = {
  API_REQUEST: {
    START: 'API.API_REQUEST.START',
    ERROR: 'API.API_REQUEST.ERROR',
    UNAUTHORIZED_ERROR: 'API.API_REQUEST.UNAUTHORIZED_ERROR',
    SUCCESS: 'API.API_REQUEST.SUCCESS',
  },
  ACCOUNT: {
    FETCH_USER_ACCOUNT: {
      START: 'API.ACCOUNT.FETCH_USER_ACCOUNT.START',
      SUCCESS: 'API.ACCOUNT.FETCH_USER_ACCOUNT.SUCCESS',
      ERROR: 'API.ACCOUNT.FETCH_USER_ACCOUNT.ERROR',
    },
    UPDATE_USER_ACCOUNT: {
      START: 'API.ACCOUNT.UPDATE_USER_ACCOUNT.START',
      SUCCESS: 'API.ACCOUNT.UPDATE_USER_ACCOUNT.SUCCESS',
      ERROR: 'API.ACCOUNT.UPDATE_USER_ACCOUNT.ERROR',
    },
    CONTACT_PERSON: {
      CREATE: {
        START: 'API.ACCOUNT.CONTACT_PERSON.CREATE.START',
        SUCCESS: 'API.ACCOUNT.CONTACT_PERSON.CREATE.SUCCESS',
        ERROR: 'API.ACCOUNT.CONTACT_PERSON.CREATE.ERROR',
      },
      REMOVE: {
        START: 'API.ACCOUNT.CONTACT_PERSON.REMOVE.START',
        SUCCESS: 'API.ACCOUNT.CONTACT_PERSON.REMOVE.SUCCESS',
        ERROR: 'API.ACCOUNT.CONTACT_PERSON.REMOVE.ERROR',
      },
      UPDATE: {
        START: 'API.ACCOUNT.CONTACT_PERSON.UPDATE.START',
        SUCCESS: 'API.ACCOUNT.CONTACT_PERSON.UPDATE.SUCCESS',
        ERROR: 'API.ACCOUNT.CONTACT_PERSON.UPDATE.ERROR',
      },
    },
    HEAD_OF_ORGANIZATION: {
      CREATE: {
        START: 'API.ACCOUNT.HEAD_OF_ORGANIZATION.CREATE.START',
        SUCCESS: 'API.ACCOUNT.HEAD_OF_ORGANIZATION.CREATE.SUCCESS',
        ERROR: 'API.ACCOUNT.HEAD_OF_ORGANIZATION.CREATE.ERROR',
      },
      REMOVE: {
        START: 'API.ACCOUNT.HEAD_OF_ORGANIZATION.REMOVE.START',
        SUCCESS: 'API.ACCOUNT.HEAD_OF_ORGANIZATION.REMOVE.SUCCESS',
        ERROR: 'API.ACCOUNT.HEAD_OF_ORGANIZATION.REMOVE.ERROR',
      },
      UPDATE: {
        START: 'API.ACCOUNT.HEAD_OF_ORGANIZATION.UPDATE.START',
        SUCCESS: 'API.ACCOUNT.HEAD_OF_ORGANIZATION.UPDATE.SUCCESS',
        ERROR: 'API.ACCOUNT.HEAD_OF_ORGANIZATION.UPDATE.ERROR',
      },
    },
    HEAD_OF_ACCOUNTS: {
      CREATE: {
        START: 'API.ACCOUNT.HEAD_OF_ACCOUNTS.CREATE.START',
        SUCCESS: 'API.ACCOUNT.HEAD_OF_ACCOUNTS.CREATE.SUCCESS',
        ERROR: 'API.ACCOUNT.HEAD_OF_ACCOUNTS.CREATE.ERROR',
      },
      REMOVE: {
        START: 'API.ACCOUNT.HEAD_OF_ACCOUNTS.REMOVE.START',
        SUCCESS: 'API.ACCOUNT.HEAD_OF_ACCOUNTS.REMOVE.SUCCESS',
        ERROR: 'API.ACCOUNT.HEAD_OF_ACCOUNTS.REMOVE.ERROR',
      },
      UPDATE: {
        START: 'API.ACCOUNT.HEAD_OF_ACCOUNTS.UPDATE.START',
        SUCCESS: 'API.ACCOUNT.HEAD_OF_ACCOUNTS.UPDATE.SUCCESS',
        ERROR: 'API.ACCOUNT.HEAD_OF_ACCOUNTS.UPDATE.ERROR',
      },
    },
  },
  USER: {
    AUTH: {
      SIGN_IN: {
        START: 'API.USER.AUTH.SIGN_IN.START',
        SUCCESS: 'API.USER.AUTH.SIGN_IN.SUCCESS',
        ERROR: 'API.USER.AUTH.SIGN_IN.ERROR',
      },
      SIGN_UP: {
        START: 'API.USER.AUTH.SIGN_UP.START',
        SUCCESS: 'API.USER.AUTH.SIGN_UP.SUCCESS',
        ERROR: 'API.USER.AUTH.SIGN_UP.ERROR',
      },
    },
    PASSWORD: {
      CHANGE: {
        START: 'API.USER.PASSWORD.CHANGE.START',
        SUCCESS: 'API.USER.PASSWORD.CHANGE.SUCCESS',
        ERROR: 'API.USER.PASSWORD.CHANGE.ERROR',
      },
      RESET: {
        START: 'API.USER.PASSWORD.RESET.START',
        SUCCESS: 'API.USER.PASSWORD.RESET.SUCCESS',
        ERROR: 'API.USER.PASSWORD.RESET.ERROR',
      },
      RESET_CONFIRM: {
        START: 'API.USER.PASSWORD.RESET_CONFIRM.START',
        SUCCESS: 'API.USER.PASSWORD.RESET_CONFIRM.SUCCESS',
        ERROR: 'API.USER.PASSWORD.RESET_CONFIRM.ERROR',
      },
      UPDATE: {
        START: 'API.USER.PASSWORD.UPDATE.START',
        SUCCESS: 'API.USER.PASSWORD.UPDATE.SUCCESS',
        ERROR: 'API.USER.PASSWORD.UPDATE.ERROR',
      },
    },
    FETCH_USER_PROFILE: {
      START: 'API.ACCOUNT.FETCH_USER_PROFILE.START',
      SUCCESS: 'API.ACCOUNT.FETCH_USER_PROFILE.SUCCESS',
      ERROR: 'API.ACCOUNT.FETCH_USER_PROFILE.ERROR',
    },
    UPDATE_USER_PROFILE: {
      START: 'API.ACCOUNT.UPDATE_USER_PROFILE.START',
      SUCCESS: 'API.ACCOUNT.UPDATE_USER_PROFILE.SUCCESS',
      ERROR: 'API.ACCOUNT.UPDATE_USER_PROFILE.ERROR',
    },
  },
  DELIVERY_ORDER: {
    CREATE_DELIVERY_ORDER: {
      START: 'API.DELIVERY_ORDER.CREATE_DELIVERY_ORDER.START',
      SUCCESS: 'API.DELIVERY_ORDER.CREATE_DELIVERY_ORDER.SUCCESS',
      ERROR: 'API.DELIVERY_ORDER.CREATE_DELIVERY_ORDER.ERROR',
    },
    FETCH_DELIVERY_ORDERS_LIST: {
      START: 'API.DELIVERY_ORDER.FETCH_DELIVERY_ORDERS_LIST.START',
      SUCCESS: 'API.DELIVERY_ORDER.FETCH_DELIVERY_ORDERS_LIST.SUCCESS',
      ERROR: 'API.DELIVERY_ORDER.FETCH_DELIVERY_ORDERS_LIST.ERROR',
    },
    FETCH_DELIVERY_ORDER_BY_ID: {
      START: 'API.DELIVERY_ORDER.FETCH_DELIVERY_ORDER_BY_ID.START',
      SUCCESS: 'API.DELIVERY_ORDER.FETCH_DELIVERY_ORDER_BY_ID.SUCCESS',
      ERROR: 'API.DELIVERY_ORDER.FETCH_DELIVERY_ORDER_BY_ID.ERROR',
    },
    FETCH_DELIVERY_ORDER_HISTORY_STATUSES_BY_ID: {
      START: 'API.DELIVERY_ORDER.FETCH_DELIVERY_ORDER_HISTORY_STATUSES_BY_ID.START',
      SUCCESS: 'API.DELIVERY_ORDER.FETCH_DELIVERY_ORDER_HISTORY_STATUSES_BY_ID.SUCCESS',
      ERROR: 'API.DELIVERY_ORDER.FETCH_DELIVERY_ORDER_HISTORY_STATUSES_BY_ID.ERROR',
    },
  },
  QUOTES: {
    FETCH_DELIVERY_ORDER_QUOTES: {
      START: 'API.QUOTES.FETCH_DELIVERY_ORDER_QUOTES.START',
      SUCCESS: 'API.QUOTES.FETCH_DELIVERY_ORDER_QUOTES.SUCCESS',
      ERROR: 'API.QUOTES.FETCH_DELIVERY_ORDER_QUOTES.ERROR',
    },
    BOOK_DELIVERY_ORDER_QUOTE: {
      START: 'API.QUOTES.BOOK_DELIVERY_ORDER_QUOTE.START',
      SUCCESS: 'API.QUOTES.BOOK_DELIVERY_ORDER_QUOTE.SUCCESS',
      ERROR: 'API.QUOTES.BOOK_DELIVERY_ORDER_QUOTE.ERROR',
    },
  },
  PAYMENT: {
    DELIVERY_ORDER: {
      PAYMENTS: {
        START: 'API.PAYMENT.DELIVERY_ORDER.PAYMENTS.START',
        SUCCESS: 'API.PAYMENT.DELIVERY_ORDER.PAYMENTS.SUCCESS',
        ERROR: 'API.PAYMENT.DELIVERY_ORDER.PAYMENTS.ERROR',
      },
    },
  },
  SUPPORT: {
    SEND: {
      START: 'API.SUPPORT.SEND.START',
      SUCCESS: 'API.SUPPORT.SEND.SUCCESS',
      ERROR: 'API.SUPPORT.SEND.ERROR',
    },
  },
};

export { API as API_ACTION_TYPES };

export const ApiActions = {
  account: {
    fetchUserAccount: createAsyncActions(API.ACCOUNT.FETCH_USER_ACCOUNT),
    updateUserAccount: createAsyncActions(API.ACCOUNT.UPDATE_USER_ACCOUNT),
    contactPerson: {
      create: createAsyncActions(API.ACCOUNT.CONTACT_PERSON.CREATE),
      update: createAsyncActions(API.ACCOUNT.CONTACT_PERSON.UPDATE),
      remove: createAsyncActions(API.ACCOUNT.CONTACT_PERSON.REMOVE),
    },
    headOfOrganization: {
      create: createAsyncActions(API.ACCOUNT.HEAD_OF_ORGANIZATION.CREATE),
      update: createAsyncActions(API.ACCOUNT.HEAD_OF_ORGANIZATION.UPDATE),
      remove: createAsyncActions(API.ACCOUNT.HEAD_OF_ORGANIZATION.REMOVE),
    },
    headOfAccounts: {
      create: createAsyncActions(API.ACCOUNT.HEAD_OF_ACCOUNTS.CREATE),
      update: createAsyncActions(API.ACCOUNT.HEAD_OF_ACCOUNTS.UPDATE),
      remove: createAsyncActions(API.ACCOUNT.HEAD_OF_ACCOUNTS.REMOVE),
    },
  },
  apiRequest: {
    start: (request, meta) => ({
      type: API.API_REQUEST.START,
      payload: {
        request,
        token: Symbol('REQUEST_TOKEN'),
      },
      meta,
    }),
    success: createAction(API.API_REQUEST.SUCCESS),
    error: createAction(API.API_REQUEST.ERROR),
    unauthorizedError: createAction(API.API_REQUEST.UNAUTHORIZED_ERROR),
  },
  deliveryOrder: {
    createDeliveryOrder: createAsyncActions(API.DELIVERY_ORDER.CREATE_DELIVERY_ORDER),
    fetchDeliveryOrdersList: createAsyncActions(API.DELIVERY_ORDER.FETCH_DELIVERY_ORDERS_LIST),
    fetchDeliveryOrderById: createAsyncActions(API.DELIVERY_ORDER.FETCH_DELIVERY_ORDER_BY_ID),
    fetchDeliveryOrderHistoryStatusesById:
      createAsyncActions(API.DELIVERY_ORDER.FETCH_DELIVERY_ORDER_HISTORY_STATUSES_BY_ID),
  },
  user: {
    auth: {
      signIn: createAsyncActions(API.USER.AUTH.SIGN_IN),
      signUp: createAsyncActions(API.USER.AUTH.SIGN_UP),
    },
    password: {
      change: createAsyncActions(API.USER.PASSWORD.CHANGE),
      reset: createAsyncActions(API.USER.PASSWORD.RESET),
      resetConfirm: createAsyncActions(API.USER.PASSWORD.RESET_CONFIRM),
      resetUpdate: createAsyncActions(API.USER.PASSWORD.UPDATE),
    },
    fetchUserProfile: createAsyncActions(API.USER.FETCH_USER_PROFILE),
    updateUserProfile: createAsyncActions(API.USER.UPDATE_USER_PROFILE),
  },
  quotes: {
    fetchDeliveryOrderQuotes: createAsyncActions(API.QUOTES.FETCH_DELIVERY_ORDER_QUOTES),
    bookDeliveryOrderQuote: createAsyncActions(API.QUOTES.BOOK_DELIVERY_ORDER_QUOTE),
  },
  payment: {
    setDeliveryOrderPaymentMethod: createAsyncActions(API.PAYMENT.DELIVERY_ORDER.PAYMENTS),
  },
  support: {
    sendComplaint: createAsyncActions(API.SUPPORT.SEND),
  },
};
